# Generated by Django 3.0.4 on 2020-03-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=40)),
                ('member_pw', models.CharField(max_length=40)),
                ('member_name', models.CharField(max_length=20)),
                ('member_email', models.CharField(max_length=50)),
                ('member_type', models.CharField(max_length=10)),
            ],
        ),
    ]
